apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-test
  template:
    metadata:
      labels:
        app: pg-test
    spec:
      containers:
        - name: pg-test
          image: craigmiller160.ddns.net:30004/pg-test:${KUBE_IMG_VERSION}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: pg-test-config
          env:
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-root-password
                  key: POSTGRES_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: pg-test-service
spec:
  type: NodePort
  selector:
    app: pg-test
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30020
      protocol: TCP
